name = "skver"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Automatically set by OpenNext
# pages_build_output_dir = ".open-next/assets"

[vars]
# Environment variables are set in the Cloudflare Pages dashboard
